### ISSUE TITLE
Fake forecast is already uncommented

### ISSUE THREAD

**Issue by arthurevans** [googlecodelabs/your-first-pwapp#1]
Step 4 says, "uncomment the line below at the bottom of your scripts/app.js file."

However, it already is:

https://github.com/googlecodelabs/your-first-pwapp/blob/master/step-04/scripts/app.js#L178

... which is a little confusing.

**Comment by petele** [comment]
Fixed in the master doc, should get rolled out shortly.

/cc @marcacohen

**Comment by mco-gh** [comment]
The step dirs reflect the end state of a given step so it's correct that the step-04 copy should have the line uncommented.
