### ISSUE TITLE
click button Add To Home Screen not response in step-8

### ISSUE THREAD

**Issue by rockey-hong** [googlecodelabs/your-first-pwapp#100]
https://weather-pwa-sample.firebaseapp.com/step-08/ also this problem

**Comment by bodadotsh** [comment]
same problem here, Chrome version 59.0.3071.115.

Could this be a browser issue as none of the other PWA sites' Add To Home Screen in the Application panel seems to work as well, e.g. https://events.google.com/io2016/

**Comment by arcturien** [comment]
+1

**Comment by mohanramphp** [comment]
Application -> Manifest -> Add to homescreen is not prompting as mentioned in the tutorial

**Comment by abbyyelton** [comment]
Would love a solution for this. I tried adding a 512x512 image as another user mentioned, but that didn't help. It seems to fetch an icon, but the notification never comes up.

**Comment by abbyyelton** [comment]
Found this solution that worked for me, enable a flag in chrome:
chrome://flags/#bypass-app-banner-engagement-checks
Make sure you restart browser after setting.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
