### ISSUE TITLE
Web page not working in UC Browser!!

### ISSUE THREAD

**Issue by Anandra-Singh** [googlecodelabs/your-first-pwapp#102]
Web page is unable to load fully in UC browser! I think it may be some problem in UC browser but this web page is unable to load completely in UC Browser!

**Comment by samdutton** [comment]
Latest version of UC might work — they've made some major updates. Could you try?

**Comment by Anandra-Singh** [comment]
ok i will try.thank you.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
