### ISSUE TITLE
app.js file not opening

### ISSUE THREAD

**Issue by codebae** [googlecodelabs/your-first-pwapp#103]
Downloaded the starter code, and opened folder in Sublime Text. App.js file won't open, and isn't even clickable in the folder tree.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
