### ISSUE TITLE
How do I remove the icon from the home screen?

### ISSUE THREAD

**Issue by tonyfarr** [googlecodelabs/your-first-pwapp#104]
Hi,
I've been able to add the icon to my home screen  following the instructions  shown in Test it out (by clicking on the Add to home screen button). I added this on my Mac and the icon shows up in the Launchpad. Very happy about this!

Now I want to remove the icon from my Launchpad. I've tried click and hold until the icons start to wiggle. However, there's no x on my pwa icon. I've also tried dragging it to the Trash, but it isn't deleted.

Can you tell me how to remove the icon please.

Thanks.
Tony.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
