### ISSUE TITLE
Its not running on local network

### ISSUE THREAD

**Issue by VinuOye** [googlecodelabs/your-first-pwapp#106]
Showing
**This site can't be reached**
192.168.0.109:8887

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
