### ISSUE TITLE
Adding to homescreen

### ISSUE THREAD

**Issue by idanen** [googlecodelabs/your-first-pwapp#107]
The icons list doesn't include the 512x512 size which is required for the prompt to be shown on devices with high resolution.
Users that follow all the instructions might get stuck when the prompt doesn't show and won't know why..
This could easily be fixed by adding this resolution also.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
