### ISSUE TITLE
Remove Web Starter Kit recommandation

### ISSUE THREAD

**Issue by sey** [googlecodelabs/your-first-pwapp#108]
On step 4, you say "and we generally recommend using Web Starter Kit". 
Then if you follow the link to Web Starter Kit you end up on a page saying "Warning: Web Starter Kit is no longer supported.". 
It doesn't feel right.

**Comment by Bound3R** [comment]
yes, this is true, it would be good to make the recommendation to view the documentation.

**Comment by sinameraji** [comment]
Yea I'm a bit confused now as there's no alternative recommendation. Wondering if I should or should not continue tutorial with WSK

**Comment by angel-luis** [comment]
Any alternative?

**Comment by samdutton** [comment]
@petele @rowan-m 

I noticed this too — I think we should remove it.

**Comment by petele** [comment]
Agreed - I've removed the recommendation from the code lab and will republish today.

**Comment by petele** [comment]
Updated in google/webfundamentals#5839
