### ISSUE TITLE
BUG!!

### ISSUE THREAD

**Issue by ALiSHERBE** [googlecodelabs/your-first-pwapp#111]
Почему тут написано одно https://codelabs.developers.google.com/codelabs/your-first-pwapp-ru/index.html?index=..%2F..%2Flang-ru#4
а в файлах написан код совсем иначе???

**Comment by samdutton** [comment]
Are you saying the instructions are different from the code?

If so, which instructions and code?

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
