### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by justiceroyale1** [googlecodelabs/your-first-pwapp#112]
On the "Use service workers to cache the forecast data (step 7)" page, you'll find this line statement <b>"Opening the data cache should should the data stored for each city."</b> I feel this is a typographic error because should is repeated twice; I believe the second <b>'should'</b> is meant to be <b>'show'</b> or some other synonym.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
