### ISSUE TITLE
Link bug

### ISSUE THREAD

**Issue by mesqueeb** [googlecodelabs/your-first-pwapp#113]
@ https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/#what_is_a_progressive_web_app

> Further Reading:
[Using app install banners] 

is not sending us to the correct page. I just get sent to the homepage of web fundamentals: https://developers.google.com/web/fundamentals/

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
