### ISSUE TITLE
Incorrect approach 'cache-then-network' in documentation code example 

### ISSUE THREAD

**Issue by dhruvmishra** [googlecodelabs/your-first-pwapp#114]
On Page: https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/

I loved the whole article, good work and thanks! But felt a need to correct below.

This is regarding the below snippet from code example:
/*
     * When the request URL contains dataUrl, the app is asking for fresh
     * weather data. In this case, the service worker always goes to the
     * network and then caches the response. This is called the "Cache then
     * network" strategy:
     * https://jakearchibald.com/2014/offline-cookbook/#cache-then-network
     */
    e.respondWith(
      caches.open(dataCacheName).then(function(cache) {
        return fetch(e.request).then(function(response){
          cache.put(e.request.url, response.clone());
          return response;
        });
      })
    );

Since in this example, we are not going to the cache first and only going to the network its not a https://jakearchibald.com/2014/offline-cookbook/#cache-then-network approach. Its actually https://jakearchibald.com/2014/offline-cookbook/#on-network-response.

**Comment by nattySP** [comment]
This is not incorrect -- I had the same thought at first but then realized, the service worker code in the codelab and in the Jake Archibald recipe is identical.  What makes it cache-then-network has to do with the code thats executed from the main page -- it sends off the network request and in parallel tries to get the data from the cache.  If its there in the cache it should return before the network request gets a response, hence cache-then-network. Same pattern is followed with app.getForecast().

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
