### ISSUE TITLE
"click inspect"

### ISSUE THREAD

**Issue by eostrom** [googlecodelabs/your-first-pwapp#116]
https://codelabs.developers.google.com/codelabs/your-first-pwapp/#5 says to "switch to the Service Worker pane in the Application panel and click inspect on the activated service worker" but I don't see anything labeled "inspect."

![2017-12-22 at 1 04 pm](https://user-images.githubusercontent.com/8683/34309640-a628d09a-e718-11e7-8333-6ae1624c72d7.jpg)

**Comment by eostrom** [comment]
The next instruction is about expecting to find something in the console, which I did by switching to the Console panel.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
