### ISSUE TITLE
Needless "removeAttribute"

### ISSUE THREAD

**Issue by angel-luis** [googlecodelabs/your-first-pwapp#118]
I think that is needless have this line:

`app.container.removeAttribute('hidden');`

Because the container element never have a hidden attribute.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
