### ISSUE TITLE
Buttons not displayed in the header of the final project

### ISSUE THREAD

**Issue by albualexandru** [googlecodelabs/your-first-pwapp#119]
When I do open the final version of the project, the buttons on the right corner do not appear in the UI. They are actionable but they just don't appear. Again this is in the final version so I assume this is a bug

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
