### ISSUE TITLE
Typo in "Opening the data cache should should the data stored for each city."

### ISSUE THREAD

**Issue by GauravGupta12** [googlecodelabs/your-first-pwapp#120]
There are two "should" in the sentence mentioned in the issue heading. It can be found out it the article, under section "Test it out" after the "Making the request" section or simply "ctrl + F" and pasting the sentence.

Thanks,
Gaurav

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
