### ISSUE TITLE
Use fetch() instead of XHR?

### ISSUE THREAD

**Issue by samdutton** [googlecodelabs/your-first-pwapp#123]
https://github.com/googlecodelabs/your-first-pwapp/blob/201582e07c11eb43bb093d1889f3118bf42f4d6c/work/scripts/app.js#L171

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
