### ISSUE TITLE
Web Starter Kit is no longer supported

### ISSUE THREAD

**Issue by camillo777** [googlecodelabs/your-first-pwapp#124]
I think you should correct the tutorial:

Web Starter Kit
Warning: Web Starter Kit is no longer supported.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
