### ISSUE TITLE
Possible mistake in official google documentation

### ISSUE THREAD

**Issue by pcalero** [googlecodelabs/your-first-pwapp#126]
In [official documentation](https://codelabs.developers.google.com/codelabs/your-first-pwapp/#6), cache-first-then-network strategy links to [cache-networks-race strategy](https://jakearchibald.com/2014/offline-cookbook/#cache-network-race). I guess it should link to [cache-then-network stategy](https://jakearchibald.com/2014/offline-cookbook/#cache-then-network).

Or maybe I am missing something.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
