### ISSUE TITLE
Refresh button without function

### ISSUE THREAD

**Issue by xpat** [googlecodelabs/your-first-pwapp#127]
Great tutorial.  But the refresh button doesn't seem to work.  After Step-09 Try it!  the site opens to https://weather-pwa-sample.firebaseapp.com/final/.  I also uploaded it to my own server and a domain of mine.  In neither case does the refresh icon function.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
