### ISSUE TITLE
This does not work on my iphone as is from a real server

### ISSUE THREAD

**Issue by kdavis45** [googlecodelabs/your-first-pwapp#129]
Had to make a couple adjustments.
First I had to add '.' or './' to pretty much every path in both manifest.jason and servicesworker.js
Also, manifest.jason needed to be in the filesToCache list for it to work correctly offline

var filesToCache = [
  './',
  './index.html',
  './favicon.ico',
  './manifest.json',
  './scripts/app.js',
  './styles/inline.css',
  './images/clear.png',
  './images/cloudy-scattered-showers.png',
  './images/cloudy.png',
  './images/fog.png',
  './images/ic_add_white_24px.svg',
  './images/ic_refresh_white_24px.svg',
  './images/partly-cloudy.png',
  './images/rain.png',
  './images/scattered-showers.png',
  './images/sleet.png',
  './images/snow.png',
  './images/thunderstorm.png',
  './images/wind.png'
];

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
