### ISSUE TITLE
Outdated code

### ISSUE THREAD

**Issue by manishjain-kcspl** [googlecodelabs/your-first-pwapp#130]
If anyone go with this tutorial, definitely the app will not give him the data what he looking for as this tutorial going with.
Just because it is outdated by getting weather data from [YQL](https://codelabs.developers.google.com/codelabs/your-first-pwapp/#6).

> var dataUrl = 'https://query.yahooapis.com/v1/public/yql';

and look app crashed here.
Issue already mentioned by other user(Jan 2017) but document is still not updated.

**Comment by arshameDEV6** [comment]
I've created an updated version of the app using OpenWeatherMaps.

https://github.com/arshameDEV6/node-pwapp-playground

Not sure what would be the best way to help update the original broken demo. My version does force users to use my node server.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
