### ISSUE TITLE
I would like to submit some translation for better zh-TW documentation

### ISSUE THREAD

**Issue by Unayung** [googlecodelabs/your-first-pwapp#131]
Hi. I'm noticing there are several translating issue on https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/?hl=zh-tw
how can I submit the correcting document for zh-TW based readers ?
let me know if I can help the community
thanks : )

**Comment by limhenry** [comment]
Hi @Unayung, you may update the translation using GitLocalize: 
https://gitlocalize.com/repo/107/zh-TW/src/content/en/fundamentals/codelabs/your-first-pwapp/index.md

or directly from GitHub:
https://github.com/google/WebFundamentals/blob/master/src/content/zh-tw/fundamentals/codelabs/your-first-pwapp/index.md

Learn how you can translate Web Fundamentals here: https://developers.google.com/web/resources/translations

**Comment by Unayung** [comment]
thanks 👍
