### ISSUE TITLE
Native Notifications Missing

### ISSUE THREAD

**Issue by DanJ210** [googlecodelabs/your-first-pwapp#133]
I've seen these type of tutorials before, have gone through them. What's always missing is any type of native access like notifications. That's a major piece that I feel is missing from this tutorial.

Don't get me wrong though as this tutorial was great and helpful and I appreciate the work. I only wish we could get to the good stuff as PWA is touted as a possible "app store app" replacement because it can tap into native API's like toast or banner notifications.

**Comment by DanJ210** [comment]
Well I didn't realize that the codelab was part of a larger module. Google took me right into the code lab and there was no mention of any notification module so I'm guessing that's where we will learn about push notifications.

**Comment by petele** [comment]
Good point, I'll look at adding that in the future!

**Comment by petele** [comment]
I've added a link in the new code lab The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
