### ISSUE TITLE
Bug!!!! 

### ISSUE THREAD

**Issue by ghost** [googlecodelabs/your-first-pwapp#134]
When I pull the bar towards the left hand side on the mobile phone and scroll down towards the end of the box, it automatically goes to the top of the box again. 
Hope this issue is fixed very soon. 
Thank you!!

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
