### ISSUE TITLE
Offline PWA not working.

### ISSUE THREAD

**Issue by vikramx20** [googlecodelabs/your-first-pwapp#137]
Manifest has an error. Offline Fetch not working.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
