### ISSUE TITLE
PWA on mobile

### ISSUE THREAD

**Issue by SevenOaksCoder** [googlecodelabs/your-first-pwapp#138]
Hi, I have been looking at ways to view PWA's on a device during development, but haven't been successful. Is there any way to view your app on a mobile device during development?

**Comment by devLarka** [comment]
did you use the webserver for chrome to enable accessible on local network? if you did, you may want to check your firewall and open the port in the link

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and recommend using Glitch, it'll make it much easier to test on mobile and desktop as you're going. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
