### ISSUE TITLE
Error in the style file for the path of the images

### ISSUE THREAD

**Issue by berthos** [googlecodelabs/your-first-pwapp#139]
The png files can't be found because of the bad path in the style file.
For example 
`.weather-forecast .icon.windy {
    background-image: url("/images/wind.png"); }`
instead of 
`.weather-forecast .icon.windy {
    background-image: url("../images/wind.png"); }`

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
