### ISSUE TITLE
It's not clear that `caches` is a global

### ISSUE THREAD

**Issue by domenic** [googlecodelabs/your-first-pwapp#14]
Using `self.caches` throughout to be consistent with `addEventListener` would be good. Also, maybe explain that `self` in a service worker is analogous to `window` in the normal page would be helpful.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
