### ISSUE TITLE
What is display: -webkit-box

### ISSUE THREAD

**Issue by fselcukcan** [googlecodelabs/your-first-pwapp#142]
I have searched it through internet but could not what it is. I could not see a value as `box` or webkit prfix version in your code i.e `-webkit-box`.
It is placed in the `inline.css` file.
What is it? Where can I find documentation about it?

**Comment by petele** [comment]
It's the old flexbox syntax, no longer used.

**Comment by aykut-rocks** [comment]
it still has to be used with line-clamp, no equivalent yet
