### ISSUE TITLE
EOL Notice: Yahoo Weather API Will Be Retired 01/03/2019

### ISSUE THREAD

**Issue by zsadler** [googlecodelabs/your-first-pwapp#143]
Yahoo Developer Network has the following EOL Notice up:

> Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 
To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service.

**Comment by ghost** [comment]
Example code no longer works because of the above mentioned EOL issue reported by @zsadler

**Comment by singhgurdip24** [comment]
Did anyone figure out now what changes do we need to make in code to get everything working?
I generated Client ID, AppId and all the required credentials. But not sure where I have to enter oAuth in code.

**Comment by davidair** [comment]
Posted a workaround in #144

**Comment by andytanghr** [comment]
I submitted a pull request that updates this code lab for the new Yahoo API.
Check it out here: https://github.com/googlecodelabs/your-first-pwapp/pull/147

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
