### ISSUE TITLE
add a new city is not working. I am able to click on + button and select on new city from available options. But two cards are not being shown on homescreen. Only newYork City weather is showing up.

### ISSUE THREAD

**Issue by singhgurdip24** [googlecodelabs/your-first-pwapp#145]

**Comment by knowlet** [comment]
Because the yahoo weather api EOL #143

**Comment by davidair** [comment]
Another dupe: https://github.com/googlecodelabs/your-first-pwapp/issues/144

**Comment by davidair** [comment]
Posted a workaround in #144

**Comment by andytanghr** [comment]
I submitted a pull request that updates this code lab for the new Yahoo API.
Check it out here: https://github.com/googlecodelabs/your-first-pwapp/pull/147

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
