### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by unitedonline** [googlecodelabs/your-first-pwapp#146]
Failed to load resource: net::ERR_NAME_NOT_RESOLVED [https://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20weather.forecast%20where%20woeid=2357536]

**Comment by douglas-kenji** [comment]
yahoo api has been retired on 01/03/2019,to make it work again you will need an API from another weather channel and modify the code to have compatibility with your new API

**Comment by andytanghr** [comment]
I submitted a pull request that updates this code lab for the new Yahoo API.
Check it out here: https://github.com/googlecodelabs/your-first-pwapp/pull/147

**Comment by dlgiant** [comment]
It worked well with @andytanghr fixes, but I wonder if locally the jQuey file was not loaded with `async`. `$` could only be recognized after removed the `async`.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
