### ISSUE TITLE
I see you have updated the code some but original download is still bad

### ISSUE THREAD

**Issue by rhunt56** [googlecodelabs/your-first-pwapp#148]
I see you made changes here: https://github.com/googlecodelabs/your-first-pwapp/pull/147/commits/14c46da0908705d002f03ac28e863448f41b69fa

but the original download files are still old ones and after going thru you mods your directions at https://codelabs.developers.google.com/codelabs/your-first-pwapp/#0 are no longer valid which keeps the app for a newbie like me from getting it working. Yes I did get the OUATH info from Yahoo.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!
