### ISSUE TITLE
Weather link no worky in Google "First PWA" tutorial

### ISSUE THREAD

**Issue by vincentwansink** [googlecodelabs/your-first-pwapp#150]
Going through Google's PWA tutorial here:  https://codelabs.developers.google.com/codelabs/your-first-pwapp/#4

At a certain point it wants the app to get weather data from Yahoo using this link:
https://query.yahooapis.com/v1/public/yql?format=json&q=

That link is no longer valid, so the weather app don't work.  Don't know what the new link should be.

**Comment by jackeymason** [comment]
Thanks for putting this together!

Yahoo's weather api didn't list a call that takes a DB query, so that needs to be changed. Maybe use: https://weather-ydn-yql.media.yahoo.com/forecastrss?location=city,state 
or
https://weather-ydn-yql.media.yahoo.com/forecastrss?woeid=id

**Comment by vincentwansink** [comment]
Thanks for that but plugging in either of those URLs, as is, doesn't work.  The original URL was appended with a query, hence the "q=".  Not sure how to make those other URLs you suggest work, but I think using either one of them would require other changes to the tutorial as well.

**Comment by jackeymason** [comment]
For sure.
Those might not even be the best URLs to start with to reduce tutorial code
churn.
Sorry, I should have provided a full answer.
When I get back to the tutorial I try to provide a full and simple solution
if possible.

Jack

**Comment by beadon1** [comment]
yep, it looks like the APIs were retired on Jan 3, 2019.

see : https://developer.yahoo.com/weather/

Would love to see an updated guide !

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/.

If you find any issues with the new codelab, please let us know!

Thanks!

**Comment by vincentwansink** [comment]
Great job on the new tutorial!  Really thorough and accurate.  No complaints.  Love the suggestion to use Glitch.

Only thing I noticed that is not 100% accurate is on the "install experience" page (https://codelabs.developers.google.com/codelabs/your-first-pwapp/#6) you said that on Windows PWAs must be uninstalled through Chrome.  That's not exactly true, as Windows generates the app with a three dot menu next to the minimize/maximize buttons in the title bar and in that menu there is an option to "Uninstall Weather..."

**Comment by petele** [comment]
Awesome - thanks, I've filed a new issue to track that!

**Comment by jackeymason** [comment]
Thank you.
I'lll give it a go.

Jack
