### ISSUE TITLE
PWA codelab source code zip does not contain step-NN directories described in the codelab

### ISSUE THREAD

**Issue by scruffycatherder** [googlecodelabs/your-first-pwapp#153]
The download source code link on https://codelabs.developers.google.com/codelabs/your-first-pwapp/#1

is https://github.com/googlecodelabs/your-first-pwapp/archive/master.zip

which downlaods your-first-pwapp-master.zip.   Here are the contents of that zip:

robert-lewis-od-mac:Downloads bobl$ unzip -l your-first-pwapp-master.zip
Archive:  your-first-pwapp-master.zip
2dfbef0f301098943dcce12cfd5d3d0f6f48238a
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  04-19-2019 09:54   your-first-pwapp-master/
      310  04-19-2019 09:54   your-first-pwapp-master/.env
       47  04-19-2019 09:54   your-first-pwapp-master/.gitignore
      343  04-19-2019 09:54   your-first-pwapp-master/.glitch-assets
      969  04-19-2019 09:54   your-first-pwapp-master/CONTRIBUTING.md
    11357  04-19-2019 09:54   your-first-pwapp-master/LICENSE
     1929  04-19-2019 09:54   your-first-pwapp-master/README.md
      722  04-19-2019 09:54   your-first-pwapp-master/package.json
        0  04-19-2019 09:54   your-first-pwapp-master/public/
        0  04-19-2019 09:54   your-first-pwapp-master/public/images/
      165  04-19-2019 09:54   your-first-pwapp-master/public/images/add.svg
      708  04-19-2019 09:54   your-first-pwapp-master/public/images/clear-day.svg
     1337  04-19-2019 09:54   your-first-pwapp-master/public/images/clear-night.svg
     3383  04-19-2019 09:54   your-first-pwapp-master/public/images/cloudy.svg
      463  04-19-2019 09:54   your-first-pwapp-master/public/images/favicon.ico
     9061  04-19-2019 09:54   your-first-pwapp-master/public/images/fog.svg
     5166  04-19-2019 09:54   your-first-pwapp-master/public/images/hail.svg
        0  04-19-2019 09:54   your-first-pwapp-master/public/images/icons/
     5754  04-19-2019 09:54   your-first-pwapp-master/public/images/icons/icon-128x128.png
     6721  04-19-2019 09:54   your-first-pwapp-master/public/images/icons/icon-144x144.png
     7330  04-19-2019 09:54   your-first-pwapp-master/public/images/icons/icon-152x152.png
     9793  04-19-2019 09:54   your-first-pwapp-master/public/images/icons/icon-192x192.png
    15072  04-19-2019 09:54   your-first-pwapp-master/public/images/icons/icon-256x256.png
     1231  04-19-2019 09:54   your-first-pwapp-master/public/images/icons/icon-32x32.png
    37670  04-19-2019 09:54   your-first-pwapp-master/public/images/icons/icon-512x512.png
      321  04-19-2019 09:54   your-first-pwapp-master/public/images/install.svg
     4124  04-19-2019 09:54   your-first-pwapp-master/public/images/partly-cloudy-day.svg
     5154  04-19-2019 09:54   your-first-pwapp-master/public/images/partly-cloudy-night.svg
     4988  04-19-2019 09:54   your-first-pwapp-master/public/images/rain.svg
      332  04-19-2019 09:54   your-first-pwapp-master/public/images/refresh.svg
     4639  04-19-2019 09:54   your-first-pwapp-master/public/images/sleet.svg
     7921  04-19-2019 09:54   your-first-pwapp-master/public/images/snow.svg
     5864  04-19-2019 09:54   your-first-pwapp-master/public/images/thunderstorm.svg
     1877  04-19-2019 09:54   your-first-pwapp-master/public/images/tornado.svg
     2228  04-19-2019 09:54   your-first-pwapp-master/public/images/wind.svg
     6930  04-19-2019 09:54   your-first-pwapp-master/public/index.html
    25274  04-19-2019 09:54   your-first-pwapp-master/public/offline.html
        0  04-19-2019 09:54   your-first-pwapp-master/public/scripts/
     8272  04-19-2019 09:54   your-first-pwapp-master/public/scripts/app.js
     1658  04-19-2019 09:54   your-first-pwapp-master/public/scripts/install.js
   242656  04-19-2019 09:54   your-first-pwapp-master/public/scripts/luxon-1.11.4.js
     1361  04-19-2019 09:54   your-first-pwapp-master/public/service-worker.js
        0  04-19-2019 09:54   your-first-pwapp-master/public/styles/
    10429  04-19-2019 09:54   your-first-pwapp-master/public/styles/inline.css
     5216  04-19-2019 09:54   your-first-pwapp-master/server.js
      242  04-19-2019 09:54   your-first-pwapp-master/watch.json
---------                     -------
   459017                     46 files

Note the lack of any directories named step-NN or work as described in the codelab.

**Comment by petele** [comment]
Sorry - I'm literally rolling out a whole new version right now. I'm just waiting for the [guide](https://g.co/codelabs/pwa) to go live. In the meantime, I've deployed the codelab at https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/, so give that a try!

If you find any issues with the new codelab, please let us know!

Thanks!
