### ISSUE TITLE
Google store

### ISSUE THREAD

**Issue by moojjoo** [googlecodelabs/your-first-pwapp#156]
Is it possible to get a PWA into the Google Store?  I am asking here, but going to do some research on my own.  Thank you for a great tutorial.   I did this in 4 hours from 3 AM to 7 AM EST.  Been very sick and was very interested in this.  Thank you again, Google.

**Comment by petele** [comment]
Check out Trusted Web Activities, they allow you to publish PWAs in the play store. We'll have a codelab coming out about them around the I/O time frame
