### ISSUE TITLE
API edit not working

### ISSUE THREAD

**Issue by halin1000** [googlecodelabs/your-first-pwapp#157]
Hello the API key isn't working, I have made my own key and updated the steps listed below but it's still giving me the fake data.

Step of tutorial:

Once the repo has loaded, edit the .env file, and update it with your DarkSky API key.
Click the Show Live button to see the PWA in action.

**Comment by petele** [comment]
What happens when you open a browser tab to https://api.darksky.net/forecast/DARKSKY_API_KEY/40.7720232,-73.9732319 but replace `DARKSKY_API_KEY` with your key?

Also, make sure everything is wrapped in double quotes and there are no extra spaces or anything like that.

**Comment by halin1000** [comment]
Atleast for me it's not working, attached are screenshots,  I also re-downloaded from github and added another new york data entry on the app to see if it would actually display current weather and time information but it doesn't seem to update it.

![Screenshot (150)](https://user-images.githubusercontent.com/49813230/56504409-6d44ec80-64e6-11e9-9389-22d6bbbc7580.png)
![Screenshot (151)](https://user-images.githubusercontent.com/49813230/56504410-6d44ec80-64e6-11e9-8cd8-d22b35ec9098.png)

**Comment by petele** [comment]
Your API key is `d82899...ab30`, you don't need to put the whole URL in there, just the API key.

You should reset your API key ASAP because it's been shared with everyone in the screenshot, so now anyone in the world can see it and use it.

**Comment by halin1000** [comment]
Thank you, it's working now!  I misunderstood the instructions much appreciated!
