### ISSUE TITLE
How can I test that this works offline?

### ISSUE THREAD

**Issue by domenic** [googlecodelabs/your-first-pwapp#16]
Especially given that I am running this on localhost, which is never "offline", how can I test that all the stuff I did in step 6 actually had an effect?

Maybe I should be testing from my phone using some kind of localhost-to-internet tunnel?

**Comment by petele** [comment]
You could turn off your web server, then also turn off your network. That'll disable the local served content, and access to the weather api?

Does that work, or am I missing your point?

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
