### ISSUE TITLE
image broken

### ISSUE THREAD

**Issue by urstory** [googlecodelabs/your-first-pwapp#161]
https://developers.google.com/web/fundamentals/codelabs/your-first-pwapp/?hl=ko

this page image broken.

**Comment by petele** [comment]
D'oh! I just pushed a new codelab and haven't created translated versions at this point, I'll need to remove the out of date ones ASAP!

**Comment by petele** [comment]
I've used machine translation to translate the new codelab into the same languages it was before! Thanks for your patience!
