### ISSUE TITLE
clone not working

### ISSUE THREAD

**Issue by ericstandlee** [googlecodelabs/your-first-pwapp#166]
I am new to programming like this, and I tried this clone multiple times. The first two times, nothing that you said would be there came across. The last times nothing.

Glitch?

**Comment by petele** [comment]
I've sometimes seen Glitch not clone stuff in properly on the first go. They may have had some production issues. I just tried, and it worked 2 out of 3 times for me. I'll rise this internally with some coworkers who have connections at Glitch.

Would you please try again and report?

**Comment by rsguillermo** [comment]
Check if you have a space between "https:" and "//" in "https://github.com/googlecodelabs/your-first-pwapp.git"

**Comment by ikinone** [comment]
The URL provided in the tutorial is incorrect, you need to remove .git from end the end

Provided: https://github.com/googlecodelabs/your-first-pwapp.git

Correct: https://github.com/googlecodelabs/your-first-pwapp

**Comment by petele** [comment]
Both should work (I've successfully used both). I believe that Glitch was just having a bad day. 

If this still isn't working for you, let's raise for the Glitch team.
