### ISSUE TITLE
indexOf() === 0 could be startsWith

### ISSUE THREAD

**Issue by domenic** [googlecodelabs/your-first-pwapp#17]
``` js
if (e.request.url.indexOf(dataUrl) === 0)
```

could be

``` js
if (e.request.url.startsWith(dataUrl))
```

Every browser that supports service workers supports startsWith.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
