### ISSUE TITLE
"Show Live" UI label and behavior changed

### ISSUE THREAD

**Issue by myakura** [googlecodelabs/your-first-pwapp#170]
in https://codelabs.developers.google.com/codelabs/your-first-pwapp/index.html?index=..%2F..io2019#1 it says:

> 6. Click the Show Live button to see the PWA in action.

However the button is slightly changed.

![opening up "show" popup in Glitch shows two submenu: one is "in a new window", and another is "next to the code"](https://user-images.githubusercontent.com/413984/58909540-55e85880-874e-11e9-9bdf-55b40ac3a2ca.png)

Now you can see the editor and app side by side, which makes the codelab easier to proceeed, but I guess the prose needs a tweak.

**Comment by myakura** [comment]
oops, with the current pwa codelab starter, the weather app shown in a frame using "Next to The Code" won't work. I guess that iframe is culprit?

**Comment by petele** [comment]
Oh good call! Updated, thanks for the tip.
