### ISSUE TITLE
`CODELAB:` marker incorrect for `FILES_TO_CACHE` section

### ISSUE THREAD

**Issue by Insulince** [googlecodelabs/your-first-pwapp#172]
I noticed in most of the copy/paste snippets there seem to be markers in the code where the lab wants us to paste the snippet. The locations are signified using `CODELAB:` followed by a message. I believe the marker used for the `FILES_TO_CACHE` section in part 5 is incorrect, it is pointing to the marker:
`// CODELAB: Update cache names any time any of the cached files change.`
When it probably was supposed to be:
`// CODELAB: Add list of files to cache here.`

**Comment by petele** [comment]
Updated, thanks for the tip!
