### ISSUE TITLE
RUN AUDITS Grammar Error

### ISSUE THREAD

**Issue by fletcher-greg** [googlecodelabs/your-first-pwapp#173]
**Section 3 Establish a baseline** 
As you'll see below the error concerns the time estimation for lighthouse to run.  Currently, it says 60-90 seconds.  But obviously, it's more like 6-9 seconds. 

 
![60-90-seconds](https://user-images.githubusercontent.com/45293706/60219714-d09b2400-9873-11e9-8ed4-108c2d206261.png)

**Comment by petele** [comment]
Updated, thanks for the tip!
