### ISSUE TITLE
Your First Progressive Web App typo

### ISSUE THREAD

**Issue by RAYDENFilipp** [googlecodelabs/your-first-pwapp#175]
There is a typo in the text: 
"you" instead of "your".
![image](https://user-images.githubusercontent.com/24476415/61576951-86f7cf00-aae9-11e9-9f9b-b6db0afb6434.png)

**Comment by MikeLuDev** [comment]
I noticed this same typo in another location:

![Annotation 2019-08-09 153004](https://user-images.githubusercontent.com/25614124/62810276-9d76c200-baba-11e9-9514-9cd95cfed4d5.png)

**Comment by petele** [comment]
Fixed both, thanks for the tip!
