### ISSUE TITLE
.env file instead of server.js

### ISSUE THREAD

**Issue by elgd** [googlecodelabs/your-first-pwapp#188]
Hi,

In the tutorial, on getting set up page [here](https://codelabs.developers.google.com/codelabs/your-first-pwapp/#1). The DarkSky api key need to be set in .env file not in server.js file.

Thank's

**Comment by petele** [comment]
Thanks - you only need to set it in `.env` if you're on Glitch, if you're running locally, you'll need to set it in `server.js`
