### ISSUE TITLE
'[ServiceWorker] Fetched&Cached Data' message should include the URL

### ISSUE THREAD

**Issue by domenic** [googlecodelabs/your-first-pwapp#19]
since it happens async, it's unclear what happened without this correspondence

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
