### ISSUE TITLE
Nonsensical code comments

### ISSUE THREAD

**Issue by arthurevans** [googlecodelabs/your-first-pwapp#2]
Step 5 has us paste the following snippet into app.js:

```
// Save list of cities to localStorage, see note below about localStorage.
app.saveSelectedCities = function() {
  var selectedCities = JSON.stringify(app.selectedCities);
  // IMPORTANT: See notes about use of localStorage.
```

The comment above apparently refers to the comment below, which refers to... The first one? Something in the codelab itself?

I spent about five minutes reading through the first half of this step trying to figure out 
which notes they were referring to. Then I finally gave up and went on to the next step, which involves pasting in a big comment... D'oh!

This was unnecessarily confusing. At a minimum, please combine these two comments into one, so they don't appear to refer to each other. "See note below" might prompt one to look lower in the codelab, if it weren't for the second comment, which confuses the issue.

**Comment by petele** [comment]
I've fixed this in master doc, should get rolled out shortly.

**Comment by petele** [comment]
cc @marcacohen

**Comment by mco-gh** [comment]
fixed doc pushed to g.co/codelabs/pwa
