### ISSUE TITLE
A single hasRequestPending flag seems really broken

### ISSUE THREAD

**Issue by domenic** [googlecodelabs/your-first-pwapp#20]
Given that you can request more than one city in parallel, a single global flag on the app for whether there's a pending request seems like it will mess things up pretty bad.

**Comment by petele** [comment]
Oh... Yah, that's a problem. Thanks for catching it.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
