### ISSUE TITLE
Annoying "Your first Progressive Web App" tooltip shows up when hovering over any text

### ISSUE THREAD

**Issue by domenic** [googlecodelabs/your-first-pwapp#21]
I can pretty consistently get this to happen by alt+tabbing away from Chrome then back and then hovering over any body text. It sticks around indefinitely.

Confirmed on both Mac and Windows.

**Comment by petele** [comment]
Marc - this is a code lab bug, not specifically a PWA issue.

**Comment by petele** [comment]
I believe this is fixed now.
