### ISSUE TITLE
DARKSKY_API_KEY API is no longer available

### ISSUE THREAD

**Issue by Nishadburhan** [googlecodelabs/your-first-pwapp#213]
darksky.net no longer accepting new signups

**Comment by washie254** [comment]
yea this really sucks. Dark sky got bought by apple

**Comment by KTibow** [comment]
Use #212 instead...

**Comment by kanreki** [comment]
Yes, using #212 is really wonderful. If you do, notice that the file names of some of the images were changed, so that the [codelab instructions](https://codelabs.developers.google.com/codelabs/your-first-pwapp/#5) for updating the FILES_TO_CACHE array don't quite work right.

**Comment by Nishadburhan** [comment]
Closed

**Comment by KTibow** [comment]
@Nishadburhan explain? why did you close your own issue as completed when this issue hasn't been resolved?
