### ISSUE TITLE
Dark Sky has joined Apple and no longer accepting new signups

### ISSUE THREAD

**Issue by Nastradamus** [googlecodelabs/your-first-pwapp#214]
Hi everyone! I can't reproduce an example, because I can't register Dark Sky API.

Will try to use fake data.

**Comment by Nastradamus** [comment]
It is duplicate of #211

**Comment by KTibow** [comment]
@Nastradamus If you still want real data, instead of using this repo, use [this one](https://github.com/elmorg/your-first-pwapp).
