### ISSUE TITLE
Why does my console show everything twice?

### ISSUE THREAD

**Issue by domenic** [googlecodelabs/your-first-pwapp#23]
Once from service-worker.js, once from :8887/service-worker.js

Chrome bug? Or something about this setup?

Confirmed on Mac and Windows.

![screenshot 25](https://cloud.githubusercontent.com/assets/617481/13545999/d5ecb330-e26c-11e5-9fe0-ba65fd761ac7.png)

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
