### ISSUE TITLE
Extra credit should recommend localForage instead of idb

### ISSUE THREAD

**Issue by domenic** [googlecodelabs/your-first-pwapp#28]
Compare how friendly the readmes are for https://www.npmjs.com/package/idb and https://mozilla.github.io/localForage/

The confusing callbacks/promises mix in the localForage docs is a bit unfortunate; [I wonder if there's a better alternative](https://twitter.com/domenic/status/706220942096257024).

**Comment by petele** [comment]
I've updated the master doc to mention localForage.
