### ISSUE TITLE
I never see a web app install banner

### ISSUE THREAD

**Issue by robdodson** [googlecodelabs/your-first-pwapp#29]
I disabled bypass user engagement checks on my phone but was still never able to see a web app install banner for https://weather-pwa-sample.firebaseapp.com/final/

**Comment by ndaidong** [comment]
Me too. Here is my app:

https://pwa-demo.firebaseapp.com

It works like a charm except of showing button for installing app in my Android phone.

**Comment by robdodson** [comment]
It looks like everything is correct but maybe the user engagement flag isn't working

**Comment by asalas91** [comment]
Everything works fine but, has anyone solved this problem?

**Comment by Famine-Life** [comment]
I also encountered this problem.， **has anyone solved this problem？**

**Comment by robdodson** [comment]
@petele 	any thoughts?

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
