### ISSUE TITLE
Delete unnecessary files from repo

### ISSUE THREAD

**Issue by petele** [googlecodelabs/your-first-pwapp#3]
The following files aren't needed for the codelab and should be deleted to not confuse students:
- [x] resources/final-gulpfile.js
- [x] resources/package.json
- [ ] firebase.json
- [x] generate-sw.js
- [x] gulpfile.js
- [x] index.html (in root only)
- [x] make-zip.sh
- [x] package.json
- [x] server.js

I also believe that /images and /styles can be yanked, but will file a separate issue for those two.

**Comment by mco-gh** [comment]
All unnecessary files deleted except for firebase.json, which is still required for deployment (step 8).

**Comment by petele** [comment]
We still need `firebase.json` removed otherwise students/participants can't run `firebase init` on their own as it blocks on an existing `firebase.json` file in the directory.

**Comment by mco-gh** [comment]
Would it be ok if I hide it somewhere? :) Like in the resources dir? Or should we just kill it?

**Comment by petele** [comment]
Hiding it is prob fine. At some point we're going to need to add back a few of the files we deleted (since they're needed for sw-precache, etc), but for the next couple of weeks it should be fine.

**Comment by mco-gh** [comment]
fixed by moving firebase.json into the resources directory.
