### ISSUE TITLE
Better 'why' for updating cacheName

### ISSUE THREAD

**Issue by Meggin** [googlecodelabs/your-first-pwapp#30]
Let's describe a bit better when the cacheName gets changed, and why that's important, and what's going on in the background if you don't update the cacheName.

**Comment by pamo** [comment]
+1, @Meggin are you referring to Step 6 on Beware of edge cases? I found the following line a bit confusing and had @petele explain it to me in better detail during the PWA Roadshow code lab.

> Cache depends on updating the cache key for every change

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
