### ISSUE TITLE
Step #2 Documentation: "PWA-GettingStarted-codelab" naming incorrect

### ISSUE THREAD

**Issue by algcifaldi** [googlecodelabs/your-first-pwapp#31]
At the very beginning of step 2, the documentation suggests to `Unpack the downloaded zip file. This will unpack a root folder (PWA-GettingStarted-codelab)` but the zip (and unpacked folder) are named `your-first-pwapp-master`

This seems like a bit of documentation that needs to be updated.

**Comment by petele** [comment]
I've updated this in the master doc, will be updated shortly.
