### ISSUE TITLE
Update sample code across service worker resources

### ISSUE THREAD

**Issue by Meggin** [googlecodelabs/your-first-pwapp#32]
We need to make sure that the sample code is up-to-date across our resources, in particular, any resources linked to in 'is service worker ready' resources list.

Also, can we organize our sample code noting the APIs that are used in them in a complete list? That way if someone wants to look at a great sample showing cache API, they can see that the sample matches what they are looking for.

**Comment by petele** [comment]
Is this specific to the code lab or an overall issue?

**Comment by Meggin** [comment]
This came out of the various resources that we link to in the code lab, as well as in the cheat sheet that we shared. So it's not specific to the codelab itself, but those that are referenced by it.

**Comment by petele** [comment]
Can you please file the issues in the specific areas that need to be updated?
