### ISSUE TITLE
Document service worker debugging

### ISSUE THREAD

**Issue by Meggin** [googlecodelabs/your-first-pwapp#33]
It's really tricky to debug your service worker. 

We should create a nice tutorial that's got some gotchas in it.

**Comment by petele** [comment]
Where should it go? And what should it cover?

**Comment by indiesquidge** [comment]
@Meggin, is something like this what you're talking about?

https://codelabs.developers.google.com/codelabs/debugging-service-workers/#0

**Comment by Meggin** [comment]
Yes, this is very cool. And love how we link to it in the new site!
