### ISSUE TITLE
Explain how to use Chrome profiles for development (instead of incognito mode)

### ISSUE THREAD

**Issue by ithinkihaveacat** [googlecodelabs/your-first-pwapp#35]
Push notifications [do not work in incognito mode](https://bugs.chromium.org/p/chromium/issues/detail?id=401439) and further the use of incognito mode for development [is discouraged](https://bugs.chromium.org/p/chromium/issues/detail?id=401439#c7).

I think the best workaround is to use a development [Chrome profiles](https://support.google.com/chrome/answer/2364824?hl=en-GB) and wipe them via `chrome://settings/clearBrowserData`. (This also has the advantage that the web server Chrome extension only needs to be present in the development profile.)

See also https://github.com/googlecodelabs/your-first-pwapp/issues/15.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
