### ISSUE TITLE
Remove images and styles directory

### ISSUE THREAD

**Issue by petele** [googlecodelabs/your-first-pwapp#4]
Remove the images and styles directory from the root of the project, the files all exist in the individual step-0x folders.

Let's hang off on this one until after IWD

**Comment by mco-gh** [comment]
I'm happy to do this now but if you'd prefer to wait for after IWD, I'm fine with that too. Will wait to hear from you, Pete.

**Comment by petele** [comment]
Let's wait until Monday, I don't want to dramatically delete files 2 days before the event! :)

**Comment by mco-gh** [comment]
sounds good. I did delete that other set of files in the related issue as you didn't express this concern but maybe I should restore those for safety?

**Comment by petele** [comment]
No, those I'm confident aren't needed, most of them were meant for the
pw-precache step or deploying to firebase.

**Comment by mco-gh** [comment]
cool, thanks! I think we're all done with the repo.

On 3 March 2016 at 13:40, Pete LePage notifications@github.com wrote:

> No, those I'm confident aren't needed, most of them were meant for the
> pw-precache step or deploying to firebase.
> 
> On Thu, Mar 3, 2016 at 8:30 AM, Marc Cohen notifications@github.com
> wrote:
> 
> > sounds good. I did delete that other set of files in the related issue as
> > you didn't express this concern but maybe I should restore those for
> > safety?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/googlecodelabs/your-first-pwapp/issues/4#issuecomment-191761980
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/googlecodelabs/your-first-pwapp/issues/4#issuecomment-191764184
> .

## 

Marc Cohen
mco@google.com
http://about.me/marc1

**Comment by mco-gh** [comment]
For now. :)

On 3 March 2016 at 14:24, Marc Cohen marccohen@google.com wrote:

> cool, thanks! I think we're all done with the repo.
> 
> On 3 March 2016 at 13:40, Pete LePage notifications@github.com wrote:
> 
> > No, those I'm confident aren't needed, most of them were meant for the
> > pw-precache step or deploying to firebase.
> > 
> > On Thu, Mar 3, 2016 at 8:30 AM, Marc Cohen notifications@github.com
> > wrote:
> > 
> > > sounds good. I did delete that other set of files in the related issue
> > > as
> > > you didn't express this concern but maybe I should restore those for
> > > safety?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/googlecodelabs/your-first-pwapp/issues/4#issuecomment-191761980
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/googlecodelabs/your-first-pwapp/issues/4#issuecomment-191764184
> > .
> 
> ## 
> 
> Marc Cohen
> mco@google.com
> http://about.me/marc1

## 

Marc Cohen
mco@google.com
http://about.me/marc1

**Comment by domenic** [comment]
I did get confused by how much stuff was in the root when first unzipping

**Comment by petele** [comment]
It's been cleaned up and should be OK now. If not, please let me know asap!
