### ISSUE TITLE
https://localhost instead of http://localhost

### ISSUE THREAD

**Issue by ithinkihaveacat** [googlecodelabs/your-first-pwapp#42]
In [step 6](https://codelabs.developers.google.com/codelabs/your-first-pwapp/#5).

**Comment by DainialPadraig** [comment]
This definitely needs more explanation. The code lab keeps emphasizing the need for SSL, but step 6 registers and runs the service worker even though Web Server for Chrome isn't capable of serving an https page. Does this mean that TLS is just strongly recommended, or is it actually a requirement for service workers in a production requirement (not localhost)?

**Comment by johvin** [comment]
@DainialPadraig I think the article [Prefer Secure Origins For Powerful New Features
](http://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features) can answer your question.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
