### ISSUE TITLE
typo in pwapp codelab step 7

### ISSUE THREAD

**Issue by sussman** [googlecodelabs/your-first-pwapp#43]
"Our app won’t work offline quite yet. We’ve implemented caching and retrieval for the app shell, but even though we’re caching the data, we’re still **dependant** on the network."

s/dependant/dependent/

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
