### ISSUE TITLE
Explain what 'bump cacheName' means

### ISSUE THREAD

**Issue by alison985** [googlecodelabs/your-first-pwapp#44]
The phrase 'bump `cacheName`' in Step 6 is assuming a lot of pre-knowledge. You're assuming people know you mean increment the string with the variable name `cacheName` at the top of service-worker.js.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
