### ISSUE TITLE
Adding close button

### ISSUE THREAD

**Issue by andreydanil** [googlecodelabs/your-first-pwapp#45]
Hi Pete,

Great progressive app tutorial. Just a quick suggestion - can you add a remove button to close the weather cards?

![image](https://cloud.githubusercontent.com/assets/5439988/14406146/72f71518-fe64-11e5-9a79-cb9fea466f1c.png)

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
