### ISSUE TITLE
Best practice for "inject the weather forecast data" in a production app

### ISSUE THREAD

**Issue by tiagozc** [googlecodelabs/your-first-pwapp#48]
In the tutorial, when it says:

...but in a production app, the latest weather forecast data would be injected by the server....

Could you please clarify a recommended way to achieve that? I mean, should I do that generating data into a script tag with the weather content (the first way I thought), or there's a better and recommended option?

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
