### ISSUE TITLE
In step 6, it should be stated that the service worker MUST be at the root level

### ISSUE THREAD

**Issue by jandsu** [googlecodelabs/your-first-pwapp#49]
As a (bit) maniac programmer, I had put the service worker under ./scripts next to app.js

It took me a while to figure out that there was a notion of _scope_ associated with the service worker script which is deduced from its URL path.

Thanks for the tuto!

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
