### ISSUE TITLE
Copy favicon.ico file to each step directory

### ISSUE THREAD

**Issue by petele** [googlecodelabs/your-first-pwapp#5]
It's not serving right now because it's in the code lab root directory as opposed to each of the step files.

**Comment by mco-gh** [comment]
fixed by commits:

https://github.com/googlecodelabs/your-first-pwapp/commit/8dd81b2d37ae81a333642c80b70ea47cfbe65387
and
https://github.com/googlecodelabs/your-first-pwapp/commit/4a3f69e5d9ae9fef622859fbb5ffbefd8f80ab02
