### ISSUE TITLE
In step 4 copying app.js gives javascript errors

### ISSUE THREAD

**Issue by cniekel** [googlecodelabs/your-first-pwapp#50]
The javascript adds listeners for butAdd, butAddCity and ButAddCancel, but only butAdd is in the html-file we're using. They will probably go into the div dialog-container later, but they're not there yet.

Adding 

```
    <button id="butAddCity" class="dialogbutton"></button>
    <button id="butAddCancel" class="dialogbutton"></button>
```

in the dialog-container fixes the errors, and doesn't show them on the screen.

**Comment by mqueirozcorreia** [comment]
I have faced the same problem today. To solve I had to open the index.html in work and the one at step 04 (from Downloaded source):

`<div class="dialog-container">
  . . .
  </div>`

to 

`<div class="dialog-container">
    <div class="dialog">
      <div class="dialog-title">Add new city</div>
      <div class="dialog-body">
        <select id="selectCityToAdd">
          <option value="austin">Austin, TX</option>
          <option value="boston">Boston, MA</option>
          <option value="chicago">Chicago, IL</option>
          <option value="portland">Portland, OR</option>
          <option value="sanfrancisco">San Francisco, CA</option>
          <option value="seattle">Seattle, WA</option>
        </select>
      </div>
      <div class="dialog-buttons">
        <button id="butAddCity" class="button">Add</button>
        <button id="butAddCancel" class="button">Cancel</button>
      </div>
    </div>
  </div>`

After doing that I faced another problem, in which I solved replacing this:

`<div class="card cardTemplate weather-forecast" hidden>
    . . .
    </div>`

To this:

`<div class="card cardTemplate weather-forecast" hidden>
      <div class="city-key" hidden></div>
      <div class="location"></div>
      <div class="date"></div>
      <div class="description"></div>
      <div class="current">
        <div class="visual">
          <div class="icon"></div>
          <div class="temperature">
            <span class="value"></span><span class="scale">°F</span>
          </div>
        </div>
        <div class="description">
          <div class="feels-like">
            <span class="value"></span><span class="scale">°F</span>
          </div>
          <div class="precip"></div>
          <div class="humidity"></div>
          <div class="wind">
            <span class="value"></span>
            <span class="scale">mph</span>
            <span class="direction"></span>°
          </div>
        </div>
      </div>
      <div class="future">
        <div class="oneday">
          <div class="date"></div>
          <div class="icon"></div>
          <div class="temp-high">
            <span class="value"></span>°
          </div>
          <div class="temp-low">
            <span class="value"></span>°
          </div>
        </div>
        <div class="oneday">
          <div class="date"></div>
          <div class="icon"></div>
          <div class="temp-high">
            <span class="value"></span>°
          </div>
          <div class="temp-low">
            <span class="value"></span>°
          </div>
        </div>
        <div class="oneday">
          <div class="date"></div>
          <div class="icon"></div>
          <div class="temp-high">
            <span class="value"></span>°
          </div>
          <div class="temp-low">
            <span class="value"></span>°
          </div>
        </div>
        <div class="oneday">
          <div class="date"></div>
          <div class="icon"></div>
          <div class="temp-high">
            <span class="value"></span>°
          </div>
          <div class="temp-low">
            <span class="value"></span>°
          </div>
        </div>
        <div class="oneday">
          <div class="date"></div>
          <div class="icon"></div>
          <div class="temp-high">
            <span class="value"></span>°
          </div>
          <div class="temp-low">
            <span class="value"></span>°
          </div>
        </div>
        <div class="oneday">
          <div class="date"></div>
          <div class="icon"></div>
          <div class="temp-high">
            <span class="value"></span>°
          </div>
          <div class="temp-low">
            <span class="value"></span>°
          </div>
        </div>
        <div class="oneday">
          <div class="date"></div>
          <div class="icon"></div>
          <div class="temp-high">
            <span class="value"></span>°
          </div>
          <div class="temp-low">
            <span class="value"></span>°
          </div>
        </div>
      </div>
    </div>
`

After doind these two replaces, all have worked for me

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
