### ISSUE TITLE
sanity check fail, unknown property name font-display, uncaught (in promise) DOMException -  Your first Progressive Web App

### ISSUE THREAD

**Issue by peterennisrda** [googlecodelabs/your-first-pwapp#51]
At this point:
![capture3884](https://cloud.githubusercontent.com/assets/1280523/16166273/cc9fb122-349e-11e6-860d-9c8cacd60397.png)

These errors:
![capture3883](https://cloud.githubusercontent.com/assets/1280523/16166285/dd6ad928-349e-11e6-8bd1-9b63972c972c.png)

**Comment by hlupico** [comment]
I am having the same issue while working through (https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/). Were you able to resolve this issue?

**Comment by peterennis** [comment]
No. I gave up and moved on to something else...

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
