### ISSUE TITLE
Icon paths in inline.css wrong

### ISSUE THREAD

**Issue by DainialPadraig** [googlecodelabs/your-first-pwapp#53]
The paths for _.weather-forecast .icon_, _#butRefresh_, and _#butAdd_ in the **inline.css** file of the work folder result in the images not being rendered. The paths should direct to the parent directory since **inline.css** is in the styles directory (i.e., ../images/). 

Of course, this may be OBE if **inline.css** is moved to the root directory by issue #4.

**Comment by Joe-Patrick** [comment]
Hi! I cannot get the images to render. the paths are like this: 
background-image: url("/images/clear.png"); } 

The full path to the images is: C:\Users\jpatr\Documents\PWA\work\images
The full path to the css is: C:\Users\jpatr\Documents\PWA\work\styles

I appreciate any help you can give. Thanks!

[PWA.zip](https://github.com/googlecodelabs/your-first-pwapp/files/2195209/PWA.zip)

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
