### ISSUE TITLE
In the step-06

### ISSUE THREAD

**Issue by hugomosh** [googlecodelabs/your-first-pwapp#56]
In the **try it** 
It doesn't load the dummy data offline
I get this error:
![captura de pantalla 2016-08-22 a las 1 30 11 p m](https://cloud.githubusercontent.com/assets/898426/17866579/9b932774-686c-11e6-8f6a-861e0fc84bf9.png)
And when I am in dev-tools I get errors when the Upload on reload is active

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
