### ISSUE TITLE
Web page text for manifest.json includes /touch/ folder for two largest icons

### ISSUE THREAD

**Issue by millarde** [googlecodelabs/your-first-pwapp#58]
This page: https://codelabs.developers.google.com/codelabs/your-first-pwapp/#7 has a "copy/paste contents..." block for manifest.json that references two icons that do not exist in the project (as best I can tell). They create a broken image link when looking at the manifest via DevTools. Changing "/touch/" to "/icons/" (which is used for the other images) fixed the issue.

I did not see the instructions for the lab in this repo or I would have sent a PR.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
