### ISSUE TITLE
Lexical Error in Step 7 > Test It Out

### ISSUE THREAD

**Issue by xpolb01** [googlecodelabs/your-first-pwapp#59]
Then go to the **Cache Storage** pane on the **Application** panel of DevTools. Expand the section and you should see the name of your app shell and data cache listed on the left-hand side. _Opening the data **cache should should** the data stored for each city._

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
