### ISSUE TITLE
App only displays initial weather data on first load

### ISSUE THREAD

**Issue by gautamarora** [googlecodelabs/your-first-pwapp#60]
When the weather app is started for the first time, the app displays the initialWeatherForecast only. The app only starts making network requests from the second refresh onwards. This makes the app ui seem incorrect the first time.

A possible fix would be to call the getForecast after the service worker registration for the first application load.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
