### ISSUE TITLE
Step 9 - Deploy to a secure host and celebrate

### ISSUE THREAD

**Issue by dbnex14** [googlecodelabs/your-first-pwapp#63]
Would be nice you provide more information on how to deploy the app to Firebase.  I tried following your steps several times without success.
For example, firebase is asking me for database file even though I choose "hosting" and not "database" option on firebase init (I issue this command from my work folder).  I was not sure what to do in this case.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!

**Comment by dbnex14** [comment]
Hate to say this but if I'm too download your code, then this isn't
tutorial, I'm not learning as I feel I'm missing important bits and
pieces.  I'll pass, thanks
