### ISSUE TITLE
Can't find the code for Progressive Webserver

### ISSUE THREAD

**Issue by gomoco** [googlecodelabs/your-first-pwapp#64]
Download the Code ( I can't Locate this Code ) Thank you!

Click the following button to download all the code for this codelab:

Unpack the downloaded zip file. This will unpack a root folder (your-first-pwapp-master), which contains one folder for each step of this codelab, along with all of the resources you will need.

The step-NN folders contain the desired end state of each step of this codelab. They are there for reference. We'll be doing all our coding work in a directory called work.

**Comment by shelDev** [comment]
Download Code button is missing from
https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/#download_the_code
- lines 905 - 906:
  `<p>Click the following button to download all the code for this codelab:</p>
  <p><a href="https://github.com/googlecodelabs/your-first-pwapp/archive/master.zip"></a></p>`

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
