### ISSUE TITLE
Grammatical error step 6

### ISSUE THREAD

**Issue by Zee-Khan** [googlecodelabs/your-first-pwapp#65]
Found error in step 6.

> OK, now **we're are** going to take a brief detour and demonstrate a gotcha...

Assuming it should either say "we are" or "we're".

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
