### ISSUE TITLE
Typo under Test it out

### ISSUE THREAD

**Issue by ldegrazia** [googlecodelabs/your-first-pwapp#66]
'Opening the data cache should should the data stored for each city.'

..should show the data...

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
