### ISSUE TITLE
No download button on Kubuntu 16.04

### ISSUE THREAD

**Issue by rmdegennaro** [googlecodelabs/your-first-pwapp#67]
An (almost) brand new installation.  I've just added a few "regular desktop" apps via apt-get and installed Google Chrome.  I can see the link in the page source, so I can continue.

**Comment by wortwart** [comment]
Same here, tested on Chrome, Firefox, and Opera in Windows. The button has a size of 0x0 pixels because it's a link without content and is displayed inline. Maybe a test for developer competence :-(

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
