### ISSUE TITLE
Your First Progressive Web App page holds a flaw

### ISSUE THREAD

**Issue by mzeeuw** [googlecodelabs/your-first-pwapp#68]
Your First Progressive Web App page: https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/ misses a button at the "Getting set up" subject:
![google progressive web app intro problem](https://cloud.githubusercontent.com/assets/389048/19554618/bae71560-96b9-11e6-8a92-712a06388357.png)

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
