### ISSUE TITLE
No code for downloading

### ISSUE THREAD

**Issue by liewsc** [googlecodelabs/your-first-pwapp#69]
Hi,

There is no button to download the code after this line:
"Click the following button to download all the code for this codelab:"

**Comment by HyunsungJo** [comment]
@liewsc i guess you could just git clone this repo for the time being : )

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
