### ISSUE TITLE
Step 6: Typo in Tip under Test It Out Section

### ISSUE THREAD

**Issue by cloverharvest** [googlecodelabs/your-first-pwapp#70]
Tip: To start fresh and clear all saved data (**localStoarge,** indexedDB data, cached files) and remove any service workers, use the Clear storage pane in the Application tab.

`localStoarge` should be `localStorage`

Step 6 => Use service workers to pre-cache the App Shell
Section => Test It Out

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
