### ISSUE TITLE
Step 9: Correct typo in aside 

### ISSUE THREAD

**Issue by cloverharvest** [googlecodelabs/your-first-pwapp#71]
If you use a different provider, be sure **they're always redirects** to HTTPS.

`they're always redirects`

should be =>

`they always redirect`

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
