### ISSUE TITLE
cache-first-then-network link on Step 7 leads to cache-network-race

### ISSUE THREAD

**Issue by pamo** [googlecodelabs/your-first-pwapp#72]
When I click on the link I'm directed to https://jakearchibald.com/2014/offline-cookbook/#cache-network-race

Was the intent to lead to [#cache-then-network](https://jakearchibald.com/2014/offline-cookbook/#cache-then-network) ?

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
