### ISSUE TITLE
Left drawer auto close on scroll

### ISSUE THREAD

**Issue by AlexMounir** [googlecodelabs/your-first-pwapp#73]
Mobile Android KitKat Lenovo A328.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
