### ISSUE TITLE
Step 05 - change localForage link

### ISSUE THREAD

**Issue by alexandreferreirafr** [googlecodelabs/your-first-pwapp#74]
Local Forage link changed to http://localforage.github.io/localForage/

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
