### ISSUE TITLE
Step 7 - app.updateForecastCard code snippet - Grammar

### ISSUE THREAD

**Issue by jinalex** [googlecodelabs/your-first-pwapp#78]
// Bail if the card has more recent data then the data

In this comment 'than' should be used in place of 'then'. Additionally the comment should specify 'recent data' refers to the data in cardLastUpdated and 'the data' refers to data passed through app.updateForecastCard to avoid confusion.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
