### ISSUE TITLE
Step 4 - Implement your App Shell - incorrect Weather API 

### ISSUE THREAD

**Issue by MeoBeoI** [googlecodelabs/your-first-pwapp#79]
In [Step 4](https://codelabs.developers.google.com/codelabs/your-first-pwapp/#3)
> A method to get the latest weather forecast data from the Firebase Public Weather API (app.getForecast).

But I think it's **Yahoo public weather API**
`var url = 'https://query.yahooapis.com/v1/public/yql?format=json&q=' + statement;`

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
