### ISSUE TITLE
Need a What to do next section/chapter

### ISSUE THREAD

**Issue by petele** [googlecodelabs/your-first-pwapp#8]
After they complete this code lab, what should they do next? Ideally I'd like them to do the push notification code lab.

It should also include deeper resources on fetch, caches, service workers, etc

Low pri - for after IWD

**Comment by mco-gh** [comment]
Feel free to add a paragraph to the "celebrate" step directing them to a reasonable next step. At any rate, this is more of an issue for the doc/codelab than the repo but happy to leave this issue intact as a memory jogger.

**Comment by petele** [comment]
Will do shortly after the first set of IWD events
