### ISSUE TITLE
Codes are not  horizontally scrollable on small screen devices making it impossible to read code on the page.

### ISSUE THREAD

**Issue by ghost** [googlecodelabs/your-first-pwapp#85]
When viewing on the small screen devices where the whole code is not visible on whole screen, the code cannot be scrolled horizontally .

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
