### ISSUE TITLE
manifest.json is 404 on final page

### ISSUE THREAD

**Issue by jiazheng** [googlecodelabs/your-first-pwapp#86]
Open the following url:

https://weather-pwa-sample.firebaseapp.com/final/

the request to manifest.json file returns 404.

https://weather-pwa-sample.firebaseapp.com/manifest.json

**Comment by Famine-Life** [comment]
在github，你修复了https://github.com/googlecodelabs/your-first-pwapp 中的路径，，但是，文档的在线预览的demo没有修改，所以[示例](https://weather-pwa-sample.firebaseapp.com/final/)报错了

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
