### ISSUE TITLE
How do you delete a city?

### ISSUE THREAD

**Issue by ddeloy** [googlecodelabs/your-first-pwapp#88]
It's apparent how to add new cities. But how do yo delete from your list?

**Comment by ddeloy** [comment]
Not ideal - but here's what i did:
app.js
// Clear local storage
  document.getElementById('butClear').addEventListener('click', function() {
    window.localStorage.clear();
   window.location.reload();
  });

index.html - I added this
<button id="butClear"  class="button">Clear local storage</button>

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
