### ISSUE TITLE
Images could be base64 encoded data URIs

### ISSUE THREAD

**Issue by mrbusche** [googlecodelabs/your-first-pwapp#89]
Instead of requiring images in the caching we could create base64 encoded data URIs and add those to the css file. I would be willing to do this as long as it's something you are looking for.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
