### ISSUE TITLE
Replace Firebase Weather Data Source with Open Weather API

### ISSUE THREAD

**Issue by petele** [googlecodelabs/your-first-pwapp#9]
According to the Firebase docs (https://www.firebase.com/docs/open-data/) the open data sets will be shutting down on March 30th.

Looks like https://openweathermap.org/api will work reasonably well.

**Comment by gautamarora** [comment]
@petele looks like it was switched to use YQL Weather API, is this issue still open? If so, I can take a look.

**Comment by petele** [comment]
Thanks @gautamarora - it was already taken care of. I'll close this.

**Comment by mgiuca** [comment]
The text of this article still says "A method to get the latest weather forecast data from the Firebase Public Weather API (app.getForecast)." Is this no longer the case?
