### ISSUE TITLE
Days are incorrect in forecast (weather is shifted by one day)

### ISSUE THREAD

**Issue by vued** [googlecodelabs/your-first-pwapp#90]
The days in the forecast are incorrect / shifted by one day.

The JSON of the yahoo API contains today as the first forecast-day, so the weather forecast is shifted by one day.

To correct this, you can start the weekdays with Sunday or skip the first forecast entry of the JSON file.

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
