### ISSUE TITLE
Step 4: Icons not showing

### ISSUE THREAD

**Issue by spndavillain** [googlecodelabs/your-first-pwapp#92]
Hello,

I just started with the project and am stuck at step 4, the icons do not show.
Here is the error am getting:

Failed to load resource: the server responded with a status of 404 (Not Found)
ic_add_white_24px.svg 
Failed to load resource: the server responded with a status of 404 (Not Found)
wind.png 
Failed to load resource: the server responded with a status of 404 (Not Found)
partly-cloudy.png 
Failed to load resource: the server responded with a status of 404 (Not Found)
thunderstorm.png 
Failed to load resource: the server responded with a status of 404 (Not Found)

Request URL:http://127.0.0.1:8887/images/ic_refresh_white_24px.svg
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:8887

Is there a fix for this?

**Comment by spndavillain** [comment]
Solved the issue.

In my css: styles/inline.css.

It was 
background-image: url("/images/clear.png"); 
and i simply changed it to
background-image: url("../images/clear.png");

**Comment by dosstx** [comment]
Please update the documentation as newbies may not figure this out. As of today, it still shows the incorrect URL for those images:
