### ISSUE TITLE
Step 6: Test it out refresh caches

### ISSUE THREAD

**Issue by PierreCavalet** [googlecodelabs/your-first-pwapp#94]
In the Step 6 Test it out, it should mention that you need to refresh caches in the chrome dev tools in order to see the cache storage.

Right clic on cache storage and refresh caches.

**Comment by invasionofsmallcubes** [comment]
Thank you Pierre. I was going mad :)

@PierreCavalet is it normal that before refreshing the cache, if I activate offline mode, it doesn't work? Did you experience the same thing?

**Comment by PierreCavalet** [comment]
Hi @invasionofsmallcubes, I don't recall this problem, I just remember going crazy trying to figure out why the cache storage was not appearing in the chrome dev tools. :)

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
