### ISSUE TITLE
Setting up firebase.json file while deploying

### ISSUE THREAD

**Issue by gauravmak** [googlecodelabs/your-first-pwapp#95]
I followed all the steps on this [page](https://codelabs.developers.google.com/codelabs/your-first-pwapp/#8) and faced an error: TypeError: targetNames.join is not a function

Found [this solution](https://stackoverflow.com/q/44022147/3113599) luckily. Please update the steps to include that.

**Comment by Simply007** [comment]
Yes as is written in link:
After `firebase init` it is required to "thick" (*) Hosting: .... by using the space for selection 

![image](https://user-images.githubusercontent.com/9218736/36900859-4345bfe4-1e25-11e8-9431-df8a13c843cf.png)

Also written here:
https://stackoverflow.com/a/47065235/3529135

Thanks for resolution
