### ISSUE TITLE
Should Indicate that SW Cache Needs Refresh to View

### ISSUE THREAD

**Issue by kkruups** [googlecodelabs/your-first-pwapp#96]
## Problem:

Service Worker **Cache Storage**  does not automatically refresh in  chrome **Application Panel**

## Details

**Section 6:**  _**Use Service Workers to Pre-Cache the App Shell**_

**Sub-Section:** **_Test It Out_**

**The following excerpt is indicated:**

Reload your page and then go to the Cache Storage pane on the Application panel of DevTools. Expand the section and you should see the name of your app shell cache listed on the left-hand side. 

However, the app shell cache does not appear listed without a right-click refresh on my system.

**Environment System:**
 Win 7 SP1 system
 Chrome version: 58.0.3029.110 (Official Build) (64-bit)

**Expected Fix:**

1.Therefore a note should be added to indicate that the **_Cache Storage_** icon  requires a right-click to access the refresh menu option.  This will help reader avoid thinking something is wrong and elimnate countless time of debugging.

or

2.Make it so that the cache automatically refreshes w/o user intervention (or both 1 and 2)

referencing issue:  https://github.com/googlecodelabs/your-first-pwapp/issues/94

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
