### ISSUE TITLE
service worker not Registered :/

### ISSUE THREAD

**Issue by asalas91** [googlecodelabs/your-first-pwapp#97]
Show message in console

Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

I'm working in localhost... 127.0.0.1 with LAMP server on Elementary Os and Vhost added

Help me, please!

**Comment by mrbusche** [comment]
What's the url for your ajax call?

**Comment by asalas91** [comment]
That happens for not reading correctly...
I thought that by registering the service-worker.js the file was automatically created...

**Comment by asalas91** [comment]
This is the code where I'm trying to register service but...

// TODO add service worker code here
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker
             .register('./service-worker.js')
             .then(function() { console.log('Service Worker Registered'); })
             .catch(function(err){
              console.log('Filed to register', err);
             });
  }

Always falls into the catch :/

**Comment by asalas91** [comment]
Well, I was making use of vhost, which is why I got error with the service-worker.js

Before my url was:
pwapp.dev/work

now my url is:
localhost/pwapp/work/ :/

it's working fine,
thanks!

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
