### ISSUE TITLE
ServiceWorker failed to install

### ISSUE THREAD

**Issue by gg4u** [googlecodelabs/your-first-pwapp#98]
I run into this issue, even from your deployed version:

https://weather-pwa-sample.firebaseapp.com/step-08/

<img width="370" alt="screen shot 2017-06-20 at 8 50 44 pm" src="https://user-images.githubusercontent.com/284214/27350355-64116820-55fa-11e7-903d-a98b679fa99b.png">

I tried to clear localstorage, but did not work.

<img width="604" alt="screen shot 2017-06-20 at 8 51 06 pm" src="https://user-images.githubusercontent.com/284214/27350369-71c19eb8-55fa-11e7-8d2a-7de441a21715.png">

I can cache elements and so does not work offline.

What could it be?

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
