### ISSUE TITLE
step 5 butAdd click event bug

### ISSUE THREAD

**Issue by sukruozdemir** [googlecodelabs/your-first-pwapp#99]
In butAdd click event, app.toggleAddDialog(false); should be app.toggleAddDialog(true); otherwise dialog not opening

**Comment by petele** [comment]
Hi!

Thanks for the feedback. I've rewritten the codelab from scratch and believe I have fixed this issue. The code has been updated, and the new [guide](https://g.co/codelabs/pwa) is now live.

If you find any issues with the new codelab, please let us know!

Thanks!
